### PR TITLE
chore: toml fix

### LINKED ISSUE #646: Move Arbiter Config out of cargo.toml and into foundry.toml

### PR DESCRIPTION
**Pull request by 0xJepsen**
Closes #646 

This also takes the fork tests out of a parallel loop so they will take load off the CI and fail less frequently

### CODE REVIEW

**Comment by 0xJepsen** [comment]
So this throws a foundry error if we put it there. Not sure where we should put this

**Comment by 0xJepsen** [comment]
Maybe move back to the arbiter.toml and we can put more higher level configuration there

File: bin/bind/test.rs [hunk 1]
```diff
@@ -0,0 +1,108 @@
+#[allow(unused_imports)]
```
Comment (0xJepsen) [inline bin/bind/test.rs:1]: Rename this file tests from test
